### ISSUE TITLE
Listing the team

### ISSUE THREAD

**Issue by catalin-hritcu** [project-everest/project-everest.github.io#2]
I think it would be great if we could list the Everest team on this website. A recent email from @vkanne-msft included such a list:

Microsoft Research
- Antoine Delignat Lavaud
- Aseem Rastogi
- Bryan Parno
- Barry Bond
- Cedric Fournet
- Chris Hawblitzel
- Jay Lorch
- Jonathan Protzenko
- Markulf Kohlweiss
- Nikhil Swamy
- Rustan Leino
- Samin Ishtiaq
- Santiago Zanella-Béguelin
- Sreekanth Kannepalli
- Srinath Setty
- Tahina Ramanandro

INRIA Paris
- Catalin Hritcu
- Jean-Karim Zinzindohoue
- Karthikeyan Bhargavan

**Comment by vkanne-msft** [comment]
updated site
