### ISSUE TITLE
Docker image availability

### ISSUE THREAD

**Issue by thomasveje** [project-everest/project-everest.github.io#6]
Hi.
The link to your Docker Hub page, 'https://hub.docker.com/r/projecteverest/everest/',
and the Docker image refered to `projecteverest/everest` appears outdated.

From the [Docker Hub page](https://hub.docker.com/u/projecteverest) (the right one for the link above?), both `projecteverest/everest-linux` and `projecteverest/vale-linux` appears to be examples of currently developed containers, but I can't pull them.

**Comment by msprotz** [comment]
Hello,

What error do you get when trying to pull everest-linux?

Thanks,

Jonathan

**Comment by thomasveje** [comment]
I'm getting the following:
```console
$ docker pull projecteverest/everest-linux
Using default tag: latest
Error response from daemon: manifest for projecteverest/everest-linux:latest not found
```
which I just realized is just because you're not using a _latest_ tag... So I tried with the newest tag from the tag pane and it started pulling.

So my "issue" has been resolved.

**Comment by msprotz** [comment]
@gugavaro is there a chance we could tag the most recent image with latest every time we push to the docker hub?

@thomasveje thanks for reporting! we're happy to take a pull request to fix the link on the website

**Comment by gugavaro** [comment]
@protz there is a couple of tricks we need to deal to achieve it, but We can certainly add this capability. I will sync with you offline on it.

@thomasveje as a work around please use the commit id (12 chars) as the tag for the image.
i.e.: 
for Everest project here is the list of commits: https://github.com/project-everest/everest/commits/master

latest commit is: 2a0a177c06d5583d08a3dbb0b8369dda17b6808c

use: docker pull projecteverest/everest-linux:2a0a177c06d5

thanks!
